### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by keirlawson** [minodisk/refactor#21]
[Enter steps to reproduce below:]

1. install atom-ternjs

**Atom Version**: 0.192.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [refactor](https://github.com/minodisk/refactor) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /home/keir/.atom/packages/refactor/lib/watcher.coffee:10

TypeError: Cannot read property 'on' of undefined
  at new Watcher (/home/keir/.atom/packages/refactor/lib/watcher.coffee:10:12)
  at Main.module.exports.Main.onCreated (/home/keir/.atom/packages/refactor/lib/refactor.coffee:46:19)
  at /home/keir/.atom/packages/refactor/lib/refactor.coffee:1:1
  at atom-workspace.<anonymous> (/usr/share/atom/resources/app/src/workspace-view.js:99:22)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:153:19)
  at TextEditorView.jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at TextEditorView.module.exports.TextEditorView.afterAttach (/usr/share/atom/resources/app/src/text-editor-view.js:178:19)
  at callAttachHooks (/usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:342:67)
  at atom-panel.PanelElement.attachedCallback (/usr/share/atom/resources/app/src/panel-element.js:44:7)
  at atom-panel-container.PanelContainerElement.panelAdded (/usr/share/atom/resources/app/src/panel-container-element.js:46:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PanelContainer.module.exports.PanelContainer.addPanel (/usr/share/atom/resources/app/src/panel-container.js:69:20)
  at Workspace.module.exports.Workspace.addPanel (/usr/share/atom/resources/app/src/workspace.js:753:45)
  at Workspace.module.exports.Workspace.addBottomPanel (/usr/share/atom/resources/app/src/workspace.js:694:19)
  at new Rename (/home/keir/.atom/packages/atom-ternjs/lib/atom-ternjs-rename.coffee:19:35)
  at new Manager (/home/keir/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:32:19)
  at Object.module.exports.activate (/home/keir/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:73:20)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:222:19)
  at /usr/share/atom/resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:434:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -4:58.9 settings-view:open (atom-text-editor.editor)
 18x -4:15.8 core:backspace (atom-text-editor.editor.mini)
  2x -4:07.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "deprecation-cop",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-go",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "vim-mode",
      "atom-lint"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-ternjs, v0.5.19
autoclose-html, v0.15.0
autocomplete-plus, v2.10.0
editorconfig, v0.3.3
highlight-line, v0.10.1
highlight-selected, v0.9.1
js-refactor, v0.3.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-jade, v0.4.0
language-typescript, v0.15.0
linter, v0.12.0
linter-jshint, v0.1.2
minimap, v4.7.6
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by minodisk** [comment]
See #30
