### ISSUE TITLE
Failed to activate the refactor package

### ISSUE THREAD

**Issue by damkraw** [minodisk/refactor#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [refactor](https://github.com/minodisk/refactor) package, v0.4.1

### Stack Trace

Failed to activate the refactor package

```
At undefined is not a function

TypeError: undefined is not a function
    at new ModuleManager (/Users/damian/.atom/packages/refactor/lib/module_manager.coffee:28:22)
    at Main.module.exports.Main.activate (/Users/damian/.atom/packages/refactor/lib/refactor.coffee:34:28)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-yaml",
      "minimap",
      "wrap-guide",
      "metrics",
      "language-toml",
      "language-mustache",
      "language-make",
      "open-on-github",
      "package-generator"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
color-picker, v1.7.0
js-refactor, v0.3.0
language-jsx, v0.1.4
layout-manager, v0.2.3
linter, v0.12.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
node-resolver, v1.0.1
npm-docs, v0.2.0
react, v0.11.6
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by kmdavis** [comment]
I'm having the same issue, since updating to Atom 0.207.0 this morning

**Comment by macpham** [comment]
Yep. Ran into the same problem as well.

**Comment by minodisk** [comment]
See #30
